# テーマ設定
#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minima
theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time machine

# ページタイトル
title: my page

#説明
description: 只今準備中

# ロゴの位置
#logo: [up]

# DLアイコン
# show_downloads: [true]

# googleアナリティクス
#google_analytics: [Your Google Analytics tracking ID]